name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Vérifier la version de Python
        run: python --version

      - name: Construire l'image Docker
        run: docker build -t devops-app:latest .

      - name: Vérifier l'image Docker
        run: docker images